// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel ApplyMask

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
Texture2D<float4> Mask;
Texture2D<float4> Image;
float4 Color;
RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void ApplyMask(uint3 id : SV_DispatchThreadID)
{
	Result[id.xy] = sqrt((1 - Mask[id.xy]) * (1 - Image[id.xy])) * Color;
}
